### ISSUE TITLE
bug??

### ISSUE THREAD

**Issue by xiangxn** [zackurben/cex.io-api-java#1]
balance result:{"error":"Nonce must be incremented"}

**Comment by zackurben** [comment]
Hey, I just updated the repo to fix this (04f1e6ddf02b65ae5b978088853146795867e60c). Let me know if you continue to get this problem.

**Comment by daniloreddy** [comment]
Hi, I run test class with my "user/key/secret" but I received:

Testing method: balance():
{"error":"Invalid signature"}

Testing method: placeOrder("GHS/BTC"):
{"error":"Invalid signature"}

Testing method: openOrders("GHS/BTC"):
{"error":"Invalid signature"}

Testing method: cancelOrder(Invalid signature):
Cancel order (ID: Invalid signature): {"error":"Invalid signature"}

Testing method: hashrate():
{"error":"Invalid signature"}

Testing method: workers():
{"error":"Invalid signature"}

Maybe is there something wrong with signature generation?

**Comment by savannt** [comment]
I am also getting Invalid Signature when I try to do some things, the best way I found to solve this was to make the function loop until it is not invalid.
